apiVersion: v1
kind: PersistentVolume
metadata:
  name: birds-pv
spec:
  capacity:
    storage: 5Gi # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Adjust the access mode as needed (e.g., ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /path/to/host/folder # Replace with the actual path on the node
